#!/usr/bin/env bash

dir=$(dirname $0)
source $dir/common

docker run \
    --interactive \
    --tty \
    --volume $(abspath $dir/..):/opt/phantom-talk \
    --publish=8000:8000 \
    --entrypoint /bin/bash \
    phantom-talk
